services:
  fastapi:
    build: ./backend/fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env          # Shared variables
      - .env.fastapi  # Service-specific
    restart: unless-stopped

  websocket:
    build: ./backend/websocket
    ports:
      - "8001:8001"
    env_file:
      - .env            # Shared variables
      - .env.websocket  # Service-specific
    restart: unless-stopped